[project]
name = "uc-intg-zwave"
version = "1.0.0"
description = "Zwave Integration for Unfolded Circle Remotes"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "zwave-js-server-python==0.56.0",
    "ucapi==0.4.0",
    "ucapi-framework==1.0.3",
    "zeroconf==0.147.0",
]
